// <auto-generated />
using System;
using Api.Infrastructure.Coletas.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(TransportadoraDbContext))]
    [Migration("20260528193804_InitialColetas")]
    partial class InitialColetas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Domain.Coletas.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Nome = "Moura Alimentos"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Nome = "ACME Distribuição"
                        });
                });

            modelBuilder.Entity("Api.Domain.Coletas.Entities.Coleta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("AtribuidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("CanceladaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClienteNome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("ColetadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DataPrevistaRetirada")
                        .HasColumnType("date");

                    b.Property<string>("DestinatarioEndereco")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("DestinatarioNome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset?>("IniciadaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MotivoCancelamento")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("MotoristaId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotoristaNome")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("RemetenteEndereco")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.Property<string>("RemetenteNome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("VeiculoId")
                        .HasColumnType("uuid");

                    b.Property<string>("VeiculoPlaca")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataPrevistaRetirada");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Coletas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            ClienteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ClienteNome = "Moura Alimentos",
                            CriadaEm = new DateTimeOffset(new DateTime(2026, 5, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataPrevistaRetirada = new DateOnly(2026, 5, 27),
                            DestinatarioEndereco = "Av. Brasil, 900",
                            DestinatarioNome = "Mercado Central",
                            Numero = "COL-20260528001",
                            Observacoes = "Coleta com janela crítica.",
                            Prioridade = "Alta",
                            RemetenteEndereco = "Rua das Palmeiras, 100",
                            RemetenteNome = "Centro de Distribuição Moura",
                            Status = "Aberta"
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            AtribuidaEm = new DateTimeOffset(new DateTime(2026, 5, 28, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ClienteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ClienteNome = "ACME Distribuição",
                            CriadaEm = new DateTimeOffset(new DateTime(2026, 5, 28, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataPrevistaRetirada = new DateOnly(2026, 5, 28),
                            DestinatarioEndereco = "Rua Norte, 12",
                            DestinatarioNome = "Loja Norte",
                            IniciadaEm = new DateTimeOffset(new DateTime(2026, 5, 28, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MotoristaId = new Guid("33333333-3333-3333-3333-333333333333"),
                            MotoristaNome = "Ana Souza",
                            Numero = "COL-20260528002",
                            Observacoes = "Conferir volumes no embarque.",
                            Prioridade = "Normal",
                            RemetenteEndereco = "Rua Industrial, 45",
                            RemetenteNome = "Galpão ACME",
                            Status = "EmColeta",
                            VeiculoId = new Guid("55555555-5555-5555-5555-555555555555"),
                            VeiculoPlaca = "ABC1D23"
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            AtribuidaEm = new DateTimeOffset(new DateTime(2026, 5, 27, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ClienteId = new Guid("11111111-1111-1111-1111-111111111111"),
                            ClienteNome = "Moura Alimentos",
                            ColetadaEm = new DateTimeOffset(new DateTime(2026, 5, 27, 13, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            CriadaEm = new DateTimeOffset(new DateTime(2026, 5, 27, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataPrevistaRetirada = new DateOnly(2026, 5, 27),
                            DestinatarioEndereco = "Av. Atlântica, 88",
                            DestinatarioNome = "Cliente Final",
                            IniciadaEm = new DateTimeOffset(new DateTime(2026, 5, 27, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MotoristaId = new Guid("44444444-4444-4444-4444-444444444444"),
                            MotoristaNome = "Bruno Lima",
                            Numero = "COL-20260527001",
                            Prioridade = "Normal",
                            RemetenteEndereco = "Rua Sul, 300",
                            RemetenteNome = "Unidade Sul",
                            Status = "Coletada",
                            VeiculoId = new Guid("66666666-6666-6666-6666-666666666666"),
                            VeiculoPlaca = "XYZ9K88"
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CanceladaEm = new DateTimeOffset(new DateTime(2026, 5, 26, 11, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ClienteId = new Guid("22222222-2222-2222-2222-222222222222"),
                            ClienteNome = "ACME Distribuição",
                            CriadaEm = new DateTimeOffset(new DateTime(2026, 5, 26, 9, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DataPrevistaRetirada = new DateOnly(2026, 5, 26),
                            DestinatarioEndereco = "Rua Industrial, 45",
                            DestinatarioNome = "ACME Matriz",
                            MotivoCancelamento = "Remetente indisponível.",
                            Numero = "COL-20260526001",
                            Observacoes = "Remetente solicitou cancelamento.",
                            Prioridade = "Alta",
                            RemetenteEndereco = "Estrada Oeste, 77",
                            RemetenteNome = "Fornecedor Oeste",
                            Status = "Cancelada"
                        });
                });

            modelBuilder.Entity("Api.Domain.Coletas.Entities.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.HasKey("Id");

                    b.ToTable("Motoristas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Nome = "Ana Souza"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Nome = "Bruno Lima"
                        });
                });

            modelBuilder.Entity("Api.Domain.Coletas.Entities.OcorrenciaColeta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColetaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("RegistradaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsuarioResponsavel")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("Id");

                    b.HasIndex("ColetaId");

                    b.ToTable("OcorrenciasColeta", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            ColetaId = new Guid("88888888-8888-8888-8888-888888888888"),
                            Descricao = "Endereço confirmado por telefone com o remetente.",
                            RegistradaEm = new DateTimeOffset(new DateTime(2026, 5, 28, 11, 15, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UsuarioResponsavel = "operador.seed"
                        });
                });

            modelBuilder.Entity("Api.Domain.Coletas.Entities.Veiculo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.ToTable("Veiculos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Descricao = "Van urbana",
                            Placa = "ABC1D23"
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            Descricao = "Caminhão baú",
                            Placa = "XYZ9K88"
                        });
                });

            modelBuilder.Entity("Api.Domain.Coletas.Entities.OcorrenciaColeta", b =>
                {
                    b.HasOne("Api.Domain.Coletas.Entities.Coleta", null)
                        .WithMany("Ocorrencias")
                        .HasForeignKey("ColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Domain.Coletas.Entities.Coleta", b =>
                {
                    b.Navigation("Ocorrencias");
                });
#pragma warning restore 612, 618
        }
    }
}
